version: '3.7'

services:
  dkkundu:
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8001:8000"
  nginx:
    build: ./nginx
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "9001:80"
      - "9002:443"
    depends_on:
      - dkkundu
