# Generated by Django 3.2 on 2022-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='cv/% Y/% m/% d/')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
